### ISSUE TITLE
preciso de nova atualização

### ISSUE THREAD

**Issue by zoreu** [cleitonleonel/script.module.rcresolver#2]
o modulo pega o link do `https://redecanaistv.com/` mas não reproduz no kodi, acho q falta alguma coisa

link: `https://redecanaistv.com/assistir-big-brother-brasil-21-bbb-21-2021-online-24-horas-ao-vivo_f9e5470c3.html`

**Comment by cleitonleonel** [comment]
O site rede canais usa um método diferente agora e ainda não tive tempo pra
rodar os links stream, não que não tenha tentado, o resolver não reproduz
os links ele apenas captura os links stream, o player é quem deve rodar os
links...
Mas como eu disse o kodi não vai conseguir rodar esses links novos, tem que
analisar bem para descobrir como rodar no kodi, vlc ou outro.

Em sáb, 24 de abr de 2021 14:46, Joel Silva ***@***.***>
escreveu:
