### ISSUE TITLE
ajuda python

### ISSUE THREAD

**Issue by zoreu** [cleitonleonel/script.module.rcresolver#3]
você consegue obter a lista de videos do canal no odysee com python?
queria só que o python pegasse o link dos videos do canal, pq o link de streaming já sei como pegar
https://odysee.com/@ancapsu:c

tentei o fiddler pra monitorar o site mais não encontrei

**Comment by cleitonleonel** [comment]
> você consegue obter a lista de videos do canal no odysee com python?
> queria só que o python pegasse o link dos videos do canal, pq o link de streaming já sei como pegar
> https://odysee.com/@ancapsu:c
> 
> tentei o fiddler pra monitorar o site mais não encontrei

Boas, posso tentar...
Vou fazer uma análise desse site e te passo as impressões...

**Comment by zoreu** [comment]
Tem essa ferramenta mas não entendi como colocar em um script e listar as páginas dos videos
https://github.com/belikor/lbrytools
