### ISSUE TITLE
não tem links mp4

### ISSUE THREAD

**Issue by zoreu** [cleitonleonel/script.module.rcresolver#4]
tem como exibir links em mp4 pra ve se roda?
m3u8 ja era

**Comment by cleitonleonel** [comment]
> tem como exibir links em mp4 pra ve se roda?
> m3u8 ja era

O site implementou recentemente o uso da cloudflare, e isso meio que travou o scraper dos dados, até tem como fazer isso usando javascript por baixo dos panos, mas não funcionaria direito no kodi, e também acabaria com a portabilidade do código.

**Comment by cleitonleonel** [comment]
> tem como exibir links em mp4 pra ve se roda?
> m3u8 ja era

Subi uma nova versão com a correção necessária para pegar os links m3u8, tente aí novamente e veja se consegue rodar esses links.
